name: ' '
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      context-path:
        required: true
        type: string
      dockerfile-path:
        required: true
        type: string


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: build and push image

    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: properties from ${{ inputs.context-path }}
      shell: bash
      working-directory: ${{ inputs.context-path }}
      id: properties
      run: |
        echo "image=$(sed -n -e '/^image/ s/.*\: *//p'  Containerfile)" >> $GITHUB_OUTPUT
        echo "tag=$(sed -n -e '/^tag/ s/.*\: *//p' Containerfile)" >> $GITHUB_OUTPUT
        echo "repo=$(sed -n -e '/^repo/ s/.*\: *//p' Containerfile)" >> $GITHUB_OUTPUT

    - name: Log in to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build ${{ inputs.context-path }} --tag ghcr.io/${{ steps.properties.outputs.repo }}/${{ steps.properties.outputs.image }}:${{ steps.properties.outputs.tag }} -f ${{ inputs.dockerfile-path }}
        docker push ghcr.io/${{ steps.properties.outputs.repo }}/${{ steps.properties.outputs.image }}:${{ steps.properties.outputs.tag }}
