name: ' '
on:
  workflow_call:
    inputs:
      context-path:
        required: true
        type: string
      dockerfile-path:
        required: true
        type: string
      image:
        required: true
        type: string
      tag:
        required: true
        type: string

env:
  repo: ghcr.io/tinkerstation/containers

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: build and push image

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Log in to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build ${{ inputs.context-path }} --tag ${{ env.repo }}/${{ inputs.image }}:${{ inputs.tag }} -f ${{ inputs.dockerfile-path }}
        docker push ${{ env.repo }}/${{ inputs.image }}:${{ inputs.tag }}
