name: build containers
on:
  workflow_dispatch:

permissions:
  contents: 'read'

jobs:
  postfix:
    uses: tinkerstation/containers/.github/workflows/reusable-workflow.yml@main
    with:
      name: postfix
      context-path: "./postfix"
      dockerfile-path: "./postfix/Containerfile"
    secrets: inherit