name: build containers
on:
  workflow_dispatch:

permissions:
  contents: 'read'

jobs:
  postfix:
    uses: tinkerstation/containers/.github/workflows/reusable-workflow.yml@main
    with:
      context-path: "./postfix"
      dockerfile-path: "./postfix/Containerfile"
      image: "postfix"
      tag: "1.0.0-3.6.5"
    secrets: inherit